INSERT INTO users (email,  password, username) VALUES ('admin@gmail.com', '$2a$04$m-Wt2Ayz.udHMZNuf-Nuc.bik61A6knckthBTrS7ca-shuVlTNZbO', 'admin');
INSERT INTO users (email,  password, username) VALUES ('user@gmail.com',  '$2a$04$m-Wt2Ayz.udHMZNuf-Nuc.bik61A6knckthBTrS7ca-shuVlTNZbO', 'user' );
INSERT INTO users (email,  password, username)VALUES ('i.kosenko@gmail.com', '$2a$04$m-Wt2Ayz.udHMZNuf-Nuc.bik61A6knckthBTrS7ca-shuVlTNZbO', 'i.kosenko' );
INSERT INTO users (email, password, username) VALUES ('o.fesenko@gmail.com',  '$2a$04$m-Wt2Ayz.udHMZNuf-Nuc.bik61A6knckthBTrS7ca-shuVlTNZbO', 'o.fesenko' );
INSERT INTO users (email,   password, username) VALUES ('v.kravchenko@gmail.com',  '$2a$04$m-Wt2Ayz.udHMZNuf-Nuc.bik61A6knckthBTrS7ca-shuVlTNZbO', 'v.kravchenko' );
INSERT INTO users (email,   password, username) VALUES ('v.dzhus@gmail.com', '$2a$04$m-Wt2Ayz.udHMZNuf-Nuc.bik61A6knckthBTrS7ca-shuVlTNZbO', 'v.dzhus' );
INSERT INTO users (email,  password, username) VALUES ('ya.tymoschenko@gmail.com', 'Yana','Tymoschenko', '$2a$04$m-Wt2Ayz.udHMZNuf-Nuc.bik61A6knckthBTrS7ca-shuVlTNZbO', 'ya.tymoschenko' );
INSERT INTO roles (role_name) VALUES ('ROLE_ADMIN');
INSERT INTO roles (role_name) VALUES ('ROLE_USER');
INSERT INTO users_roles (user_id, role_id) VALUES (1, 1);
INSERT INTO users_roles (user_id, role_id) VALUES (2, 2);
INSERT INTO users_roles (user_id, role_id) VALUES (3, 2);
INSERT INTO users_roles (user_id, role_id) VALUES (4, 2);
INSERT INTO users_roles (user_id, role_id) VALUES (5, 2);
INSERT INTO users_roles (user_id, role_id) VALUES (6, 2);
INSERT INTO users_roles (user_id, role_id) VALUES (7, 2);
