INSERT INTO users (email, firstname, lastname, password, username, active) VALUES ('admin@gmail.com', 'Serhii','Herashchenko', '$2a$04$m-Wt2Ayz.udHMZNuf-Nuc.bik61A6knckthBTrS7ca-shuVlTNZbO', 'admin', TRUE);
INSERT INTO users (email, firstname, lastname, password, username, active) VALUES ('user@gmail.com', 'Alina','Parubets', '$2a$04$m-Wt2Ayz.udHMZNuf-Nuc.bik61A6knckthBTrS7ca-shuVlTNZbO', 'user', FALSE );
INSERT INTO users (email, firstname, lastname, password, username, active) VALUES ('i.kosenko@gmail.com', 'Irina','Kosenko', '$2a$04$m-Wt2Ayz.udHMZNuf-Nuc.bik61A6knckthBTrS7ca-shuVlTNZbO', 'i.kosenko', TRUE );
INSERT INTO users (email, firstname, lastname, password, username, active) VALUES ('o.fesenko@gmail.com', 'Olexandr','Fesenko', '$2a$04$m-Wt2Ayz.udHMZNuf-Nuc.bik61A6knckthBTrS7ca-shuVlTNZbO', 'o.fesenko', TRUE );
INSERT INTO users (email, firstname, lastname, password, username, active) VALUES ('v.kravchenko@gmail.com', 'Vasyl','Kravchenko', '$2a$04$m-Wt2Ayz.udHMZNuf-Nuc.bik61A6knckthBTrS7ca-shuVlTNZbO', 'v.kravchenko', TRUE );
INSERT INTO users (email, firstname, lastname, password, username, active) VALUES ('v.dzhus@gmail.com', 'Vlad','Dzhus', '$2a$04$m-Wt2Ayz.udHMZNuf-Nuc.bik61A6knckthBTrS7ca-shuVlTNZbO', 'v.dzhus', TRUE );
INSERT INTO users (email, firstname, lastname, password, username, active) VALUES ('ya.tymoschenko@gmail.com', 'Yana','Tymoschenko', '$2a$04$m-Wt2Ayz.udHMZNuf-Nuc.bik61A6knckthBTrS7ca-shuVlTNZbO', 'ya.tymoschenko', TRUE );
INSERT INTO roles (role_name) VALUES ('ROLE_ADMIN');
INSERT INTO roles (role_name) VALUES ('ROLE_USER');
INSERT INTO users_roles (user_id, role_id) VALUES (1, 1);
INSERT INTO users_roles (user_id, role_id) VALUES (2, 2);
INSERT INTO users_roles (user_id, role_id) VALUES (3, 2);
INSERT INTO users_roles (user_id, role_id) VALUES (4, 2);
INSERT INTO users_roles (user_id, role_id) VALUES (5, 2);
INSERT INTO users_roles (user_id, role_id) VALUES (6, 2);
INSERT INTO users_roles (user_id, role_id) VALUES (7, 2);
INSERT INTO participants (participant_name, participant_address) VALUES ('ПАТ "ВБР"', 'м.Київ, вул.В.Чорновола, 25');
INSERT INTO participants (participant_name, participant_address) VALUES ('ТОВ "ДИАД"', 'м.Київ, вул.Хрещатик, 36');
INSERT INTO participants (participant_name, participant_address) VALUES ('ТОВ "КВАДРУМ-АСН"', 'м.Київ, вул.Велика Васильківська, 12');
INSERT INTO participants (participant_name, participant_address) VALUES ('ФОП Камаралі Р.В.', 'м.Київ, вул.Оболонська, 9а');
INSERT INTO participants (participant_name, participant_address) VALUES ('ФОП Третьяков А.С.', 'м.Київ, вул.Оболонська, 9а');
INSERT INTO participants (participant_name, participant_address) VALUES ('ПАТ "ДАТАГРУП"', 'м.Київ, пр.Перемоги, 43');
INSERT INTO participants (participant_name, participant_address) VALUES ('ПрАТ "Київстар"', 'м.Київ, вул.Дегтярівська, 44');
INSERT INTO participants (participant_name, participant_address) VALUES ('Прат "Лайфселл"', 'м.Київ, вул.Святошинська, 1');
INSERT INTO participants (participant_name, participant_address) VALUES ('ФОП Шаповал Т.С.', 'м.Київ, вул.В.Чорновола, 9а');
INSERT INTO courts (court_name) VALUES ('Голосіївський районний суд м. Києва');
INSERT INTO courts (court_name) VALUES ('Дніпровський районний суд м. Києва');
INSERT INTO courts (court_name) VALUES ('Шевченківський районний суд м. Києва');
INSERT INTO courts (court_name) VALUES ('Святошинський районний суд м. Києва');
INSERT INTO courts (court_name) VALUES ('Соломянський районний суд м. Києва');
INSERT INTO courts (court_name) VALUES ('Дарницький районний суд м. Києва');
INSERT INTO courts (court_name) VALUES ('Деснянський районний суд м. Києва');
INSERT INTO causes (court_id, user_id, next_date, number, price) VALUES (1, 3, '2017-10-30 11:00:00', '123К-10', 10123.01);
INSERT INTO causes (court_id, user_id, next_date, number, price) VALUES (2, 4, '2017-10-10 11:00:00', '123К-11', 12000);
INSERT INTO causes (court_id, user_id, next_date, number, price) VALUES (3, 4, '2017-01-10 11:00:00', '123К-12', 100000.50);
INSERT INTO causes (court_id, user_id, next_date, number, price) VALUES (5, 5, '2017-10-30 11:00:00', '123К-13', 23123.05);
INSERT INTO causes (court_id, user_id, next_date, number, price) VALUES (5, 6, '2017-10-30 11:00:00', '123К-14', 44178.12);
INSERT INTO causes (court_id, user_id, next_date, number, price) VALUES (2, 7, '2017-10-30 11:00:00', '123К-15', 1000.01);
INSERT INTO descriptions (cause_id, description_text, description_date) VALUES (1, 'Подано позов до суду', '2017-10-30 11:00:00');
INSERT INTO descriptions (cause_id, description_text, description_date) VALUES (1, 'Перше засідання суду', '2017-10-30 11:00:00');
INSERT INTO descriptions (cause_id, description_text, description_date) VALUES (2, 'Подано позов до суду', '2017-10-30 11:00:00');
INSERT INTO descriptions (cause_id, description_text, description_date) VALUES (3, 'Подано позов до суду', '2017-10-30 11:00:00');
INSERT INTO descriptions (cause_id, description_text, description_date) VALUES (3, 'Перше засідання суду', '2017-10-30 11:00:00');
INSERT INTO descriptions (cause_id, description_text, description_date) VALUES (4, 'Подано позов до суду', '2017-10-30 11:00:00');
INSERT INTO causes_participants (cause_id, participant_id) VALUES (1, 1);
INSERT INTO causes_participants (cause_id, participant_id) VALUES (1, 2);
INSERT INTO causes_participants (cause_id, participant_id) VALUES (2, 1);
INSERT INTO causes_participants (cause_id, participant_id) VALUES (2, 3);
INSERT INTO causes_participants (cause_id, participant_id) VALUES (3, 1);
INSERT INTO causes_participants (cause_id, participant_id) VALUES (3, 4);
INSERT INTO causes_participants (cause_id, participant_id) VALUES (4, 1);
INSERT INTO causes_participants (cause_id, participant_id) VALUES (4, 5);
INSERT INTO causes_participants (cause_id, participant_id) VALUES (5, 1);
INSERT INTO causes_participants (cause_id, participant_id) VALUES (5, 6);
INSERT INTO causes_participants (cause_id, participant_id) VALUES (5, 7);
INSERT INTO causes_participants (cause_id, participant_id) VALUES (5, 8);
